services:
  app:
    container_name: ${APP_NAME}
    build: .
    restart: always
    env_file: .env
    ports:
      - ${GRPC_HOST}:${GRPC_PORT}:${GRPC_PORT}
  db:
    container_name: ${APP_NAME}_db
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
    ports:
      - ${DB_PORT}:${DB_PORT}