services:
  app:
    container_name: ${APP_NAME}
    build: .
    restart: always
    env_file: .env
    ports:
      - ${GRPC_HOST}:${GRPC_PORT}:${GRPC_PORT}

  db:
    container_name: ${APP_NAME}_db
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
    volumes:
      - /postgresql/data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:${DB_PORT}

  jaeger:
    container_name: ${APP_NAME}_trace
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"

  #prometheus:
  #  image: prom/prometheus:latest
  #  volumes:
  #    - ./prometheus.yaml:/etc/prometheus/prometheus.yml
  #  ports:
  #    - "9090:9090"