// Code generated by MockGen. DO NOT EDIT.
// Source: exchange.go

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "Garantex_grpc/internal/domain"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockExchanger is a mock of Exchanger interface.
type MockExchanger struct {
	ctrl     *gomock.Controller
	recorder *MockExchangerMockRecorder
}

// MockExchangerMockRecorder is the mock recorder for MockExchanger.
type MockExchangerMockRecorder struct {
	mock *MockExchanger
}

// NewMockExchanger creates a new mock instance.
func NewMockExchanger(ctrl *gomock.Controller) *MockExchanger {
	mock := &MockExchanger{ctrl: ctrl}
	mock.recorder = &MockExchangerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExchanger) EXPECT() *MockExchangerMockRecorder {
	return m.recorder
}

// GetAndSaveRates mocks base method.
func (m *MockExchanger) GetAndSaveRates(ctx context.Context, market string) (domain.Rates, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAndSaveRates", ctx, market)
	ret0, _ := ret[0].(domain.Rates)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAndSaveRates indicates an expected call of GetAndSaveRates.
func (mr *MockExchangerMockRecorder) GetAndSaveRates(ctx, market interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAndSaveRates", reflect.TypeOf((*MockExchanger)(nil).GetAndSaveRates), ctx, market)
}
