// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.12.4
// source: exchange.proto

package exchange_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ExchangeGRPC_GetRates_FullMethodName = "/exchange_v1.ExchangeGRPC/GetRates"
)

// ExchangeGRPCClient is the client API for ExchangeGRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExchangeGRPCClient interface {
	GetRates(ctx context.Context, in *GetRatesRequest, opts ...grpc.CallOption) (*GetRatesResponse, error)
}

type exchangeGRPCClient struct {
	cc grpc.ClientConnInterface
}

func NewExchangeGRPCClient(cc grpc.ClientConnInterface) ExchangeGRPCClient {
	return &exchangeGRPCClient{cc}
}

func (c *exchangeGRPCClient) GetRates(ctx context.Context, in *GetRatesRequest, opts ...grpc.CallOption) (*GetRatesResponse, error) {
	out := new(GetRatesResponse)
	err := c.cc.Invoke(ctx, ExchangeGRPC_GetRates_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExchangeGRPCServer is the server API for ExchangeGRPC service.
// All implementations must embed UnimplementedExchangeGRPCServer
// for forward compatibility
type ExchangeGRPCServer interface {
	GetRates(context.Context, *GetRatesRequest) (*GetRatesResponse, error)
	mustEmbedUnimplementedExchangeGRPCServer()
}

// UnimplementedExchangeGRPCServer must be embedded to have forward compatible implementations.
type UnimplementedExchangeGRPCServer struct {
}

func (UnimplementedExchangeGRPCServer) GetRates(context.Context, *GetRatesRequest) (*GetRatesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRates not implemented")
}
func (UnimplementedExchangeGRPCServer) mustEmbedUnimplementedExchangeGRPCServer() {}

// UnsafeExchangeGRPCServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExchangeGRPCServer will
// result in compilation errors.
type UnsafeExchangeGRPCServer interface {
	mustEmbedUnimplementedExchangeGRPCServer()
}

func RegisterExchangeGRPCServer(s grpc.ServiceRegistrar, srv ExchangeGRPCServer) {
	s.RegisterService(&ExchangeGRPC_ServiceDesc, srv)
}

func _ExchangeGRPC_GetRates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExchangeGRPCServer).GetRates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExchangeGRPC_GetRates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExchangeGRPCServer).GetRates(ctx, req.(*GetRatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ExchangeGRPC_ServiceDesc is the grpc.ServiceDesc for ExchangeGRPC service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExchangeGRPC_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "exchange_v1.ExchangeGRPC",
	HandlerType: (*ExchangeGRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRates",
			Handler:    _ExchangeGRPC_GetRates_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "exchange.proto",
}
